version: '3'
services:
  api-server:
    build: ./api-server
    ports:
      - 8080:8080
    image: apiserver:1.0
    container_name: api_server_container
  home:
    build: 
      context: ./home
    volumes:
      - .:/home
    ports:
      - 3000:3000
    image: products_home:1.0
    container_name: products_home_container
    command: pnpm serve --host 0.0.0.0
  pdp:
    build: 
      context: ./pdp
    volumes:
      - .:/pdp
    ports:
      - 3001:3001
    image: products_pdp:1.0
    container_name: products_pdp_container
    command: pnpm serve --host 0.0.0.0


