version: '3'
services:
  api-server:
    build: ./api-server
    # volumes:
    #   - .:/app
    ports:
      - 8080:8080
    image: apiserver:1.0
    container_name: api_server_container
  home:
    build: 
      context: ./home
    # volumes:
    #   - .home:/app
    ports:
      - 3000:3000
    image: products_home:1.0
    container_name: products_home_container
    command: pnpm serve --host 0.0.0.0
  pdp:
    build: 
      context: ./pdp
    # volumes:
    #   - .:/app
    ports:
      - 3001:3001
    image: products_pdp:1.0
    container_name: products_pdp_container
    command: pnpm serve --host 0.0.0.0
  cart:
    build: 
      context: ./cart
    # volumes:
    #   - .:/app
    ports:
      - 3002:3002
    image: products_cart:1.0
    container_name: products_cart_container
    command: pnpm serve --host 0.0.0.0
  main-app:
    build: 
      context: ./main-app
    # volumes:
    #   - .:/app
    ports:
      - 3005:3005
    image: products_main:1.0
    container_name: products_main_container
    command: pnpm serve --host 0.0.0.0